wolfsyntax/greebu-ux

src/assets/css/artist-ui.css, src/views/Artist/Index.vue
=> design right sidebar and artist post

src/assets/carousel-icon-next.svg, src/assets/css/artist-ui.css, src/router/index.js, src/views/Artist/Index.vue
=> Restore icon next

src/assets/css/artist-ui.css, src/style.css, src/views/Artist/AddMember.vue, src/views/Artist/Profile.vue, src/views/BasicInformation/Index.vue
=> Crate Song stepper

src/components/Artist/ArtistDetails.vue, src/components/Artist/Card.vue, src/style.css, src/views/Artist/Index.vue, src/views/BasicInformation/Index.vue, src/views/Homepage/Artist.vue
#artist details modal component
=> artist details modal component

src/components/Artist/Card.vue, src/components/Home/Feature.vue, src/components/Home/FeaturedArtists.vue, src/views/Homepage/Artist.vue
=> artist card

src/components/Auth/Account/Settings/Menu/Request Application/Accepted.vue, src/components/Auth/Account/Settings/Menu/Request Application/Card.vue, src/components/Auth/Account/Settings/Menu/Request Application/Denied.vue, src/components/Auth/Account/Settings/Menu/Request Application/Index.vue, src/components/Auth/Account/Settings/Menu/Request Application/PendingApplication.vue, src/components/Auth/Account/Settings/Menu/Request Application/RequestApplicationModal.vue, src/store/modules/organizers/actions.js, src/store/modules/organizers/mutations.js, src/store/modules/organizers/state.js, src/store/mutations.js, src/store/state.js, src/views/Artist/Form/ProposalForm.vue
1. Update for rendering proposal (organizer - request application menu)
2. Update Proposal View details modal content
3. Update Vuex for Fetching Proposals (Organizer view)
4. Create new vuex action for accepting / declining a proposal
=> Update for fetching and accepting/declining proposals

src/components/Auth/Account/Settings/Menu/Notifications.vue, src/store/index.js, src/store/modules/notifications/actions.js, src/store/modules/notifications/getters.js, src/store/modules/notifications/index.js, src/store/modules/notifications/mutations.js, src/store/modules/notifications/state.js, src/store/modules/organizers/actions.js
1. Notification
2. Create a new notification module for notifications
- fetch all notification
- mark specific notification as read
- mark all as read
=> Update for notification - add vuex module

src/assets/css/artist-ui.css, src/components/Auth/Account/Settings/Menu/Notification/Card.vue, src/components/Auth/Account/Settings/Menu/Notifications.vue, src/components/Layouts/Layout.vue, src/store/modules/profiles/actions.js, src/style.css
- design Notifications tab
- design bell dropdown notif
=> design Notifications

index.html, src/assets/css/artist-ui.css, src/components/Auth/Account/Settings/Menu/My Proposal/AcceptedProposals.vue, src/components/Auth/Account/Settings/Menu/My Proposal/DeniedProposals.vue, src/components/Auth/Account/Settings/Menu/My Proposal/Offers.vue, src/components/Auth/Account/Settings/Menu/My Proposal/ProposalModal.vue, src/components/Auth/Account/Settings/Menu/My Proposal/SubmittedProposal.vue, src/components/Auth/Account/Settings/Menu/My Proposal/ViewProposalModal.vue, src/components/Post/Index.vue, src/style.css, src/views/Artist/Profile.vue, src/views/Organizer/Profile.vue
- design Submitted Proposal, Accepted and Denied Proposals 
- design View Porposal modal
- fix Address input field on laptop sizes 
- fix 1440px Artist form and Profile
=> design Artist - My Proposal

src/assets/css/artist-ui.css, src/components/Auth/Account/Settings/Menu/Collaboration.vue, src/components/Auth/Account/Settings/Menu/Collaboration/AcceptedCollaboration.vue, src/components/Auth/Account/Settings/Menu/Collaboration/Denied.vue, src/components/Auth/Account/Settings/Menu/Collaboration/EventCardProposal.vue, src/components/Auth/Account/Settings/Menu/Collaboration/Index.vue, src/components/Auth/Account/Settings/Menu/Collaboration/PendingRequest.vue, src/components/Auth/Account/Settings/Menu/Collaboration/PendingResponse.vue, src/components/Auth/Account/Settings/Menu/Collaboration/ViewProposalModal.vue, src/components/Auth/Account/Settings/Menu/My Proposal/EventCardProposal.vue, src/components/Auth/Account/Settings/Menu/Request Application/Card.vue, src/components/Auth/Account/Settings/Menu/Request Application/RequestApplicationModal.vue, src/style.css, src/views/Artist/Library.vue, src/views/Auth/Account/Setting.vue
Artist Account:
- fix 1440px design on proposal form 
- design Collaboration - Pending Request 
- design Collaboration - Pending Response 
- design Collaboration - Accepted Collaboration
- design Collaboration - Denied
=> design artist collaboration

src/components/Auth/Account/Settings/Menu/Request Application/Card.vue
Current: event creation date
Fix: proposal submission date
=> instead of event creation date to proposal submission date

package-lock.json, package.json, src/assets/css/artist-ui.css, src/components/Auth/Events/FormModal.vue, src/components/Auth/Events/LookModal.vue, src/components/DeleteConfirmation.vue, src/components/Loading.vue, src/components/Upload Song/Details/UploadSong.vue, src/style.css, src/views/Artist/Form/ProposalForm.vue, src/views/Artist/Profile.vue
- design Upload Song
- design 1440px Upload Song
=> design Upload Song

src/components/Auth/Account/Settings/Menu/Managed Subscriptions/CancelSubscriptionModal.vue, src/components/Auth/Account/Settings/Menu/Managed Subscriptions/Index.vue, src/components/Auth/Account/Settings/Menu/Managed Subscriptions/InvoiceDetailsModal.vue, src/components/Auth/Account/Settings/Menu/Managed Subscriptions/PaymentHistoryModal.vue, src/components/Auth/Account/Settings/Menu/Managed Subscriptions/PaymentMethodModal.vue, src/style.css
Artist Account (Managed Subscriptions):
- design 1440px Payment History modal
- design payment - View Details modal 
- design 1440px payment - View Details modal 
- design change payment method
=> design payment method & invoice modal

src/assets/css/artist-ui.css, src/components/Artist/Card.vue, src/components/Auth/Events/LookModal.vue, src/components/FilterResults.vue, src/style.css, src/views/Artist/Library.vue, src/views/Homepage/Artist.vue, src/views/Homepage/Event.vue
- Events page - fix search bar design
- Events / Artist page - add new filters 
- delete duplicate stylings 
- add Number of artist field in create an event modal
Artist Account:
Library:
- design Album|Songs list - other albums 
- 1440px design Album|Songs list
=> update Filter design

src/assets/css/artist-ui.css, src/components/Dashboard/Tabs/Events/EventCard.vue, src/components/Events/ViewEventDetailsModal.vue, src/style.css, src/views/Homepage/Artist.vue, src/views/Homepage/Event.vue, src/views/Organizer/Forms/SocialMedia.vue
Organizer Account:
- remove duplicate stylings 
- Organizer profile - fix overlapping event types 
- Organizer profile - Events tab - fix overlapping date wrapper
- change width/design of create an event modal in 1440px
=> remove duplicate stylings

src/assets/css/artist-ui.css, src/components/Artist/ArtistDetails.vue, src/components/Auth/SocialLogin.vue, src/components/Dashboard/Artist.vue, src/style.css, src/views/Artist/Form/AddMember.vue, src/views/Artist/Form/SocialMedia.vue, src/views/Artist/Profile.vue, src/views/Homepage/Event.vue, src/views/Organizer/Forms/SocialMedia.vue, src/views/Organizer/Forms/StaffForm.vue
- Organizer form - fix/design add social media accounts modal 
- Organizer form - fix/design add staff members modal
- Events page - design pagination tab
=> design tab and modal

src/components/Auth/SocialLogin.vue, src/components/Auth/Verify.vue, src/store/actions.js, src/store/mutations.js, src/store/state.js, src/views/Auth/Verify.vue
Add attribute type to buttons to prevent submitting forms in login / registration form via social media buttons
Revise process on authenticating
=> Authentication via social media login 

src/assets/css/artist-ui.css, src/views/Artist/Profile.vue, src/views/Organizer/Profile.vue
=> Modify profile subheader

src/router/index.js, src/style.css, src/views/Auth/Register.vue, src/views/CookiesPolicy.vue, src/views/PrivacyPolicy.vue, src/views/Terms.vue
=> policy such as term, privacy, cookies

src/style.css, src/views/CookiesPolicy.vue, src/views/PrivacyPolicy.vue, src/views/Terms.vue
=> Updated Policy UI Design

src/components/Layouts/Layout.vue, src/style.css
fix the navigation bar moved to the right side
=> Navigational bar | This needs to be implemented to all Accounts | Move the Navigational bar to the right

src/components/Layouts/Layout.vue
Added link for cookies in Footer
=> added link for cookies

src/components/Auth/Events/FormModal.vue
=> fix the remove button

src/components/Auth/Events/FormModal.vue, src/style.css, src/views/Auth/Forgot.vue, src/views/Auth/ResetPassword.vue
- loading indicator on Forgot Pass
- resend link button
=> loading indicator

src/views/Homepage/Event.vue
=> FIXED Event page | Event subtitle

src/components/Home/Feature.vue
- Homepage | Discover the Easy Way to Book Your Dream Artist section | Subtitle
https://trello.com/c/D1QlZGff/157-homepage-discover-the-easy-way-to-book-your-dream-artist-section-subtitle
- Homepage | Choose available artist to perform in your event section | bullet points
https://trello.com/c/yeDtVKto/158-homepage-choose-available-artist-to-perform-in-your-event-section-bullet-points
- Homepage | Set and book your event section | bullet points
https://trello.com/c/39DTWAP4/159-homepage-set-and-book-your-event-section-bullet-points
- Homepage | customer review section | subtitle
https://trello.com/c/dBnfeo8b/164-homepage-customer-review-section-subtitle
- Homepage | Songs for every Occasion section | sub title
https://trello.com/c/2oLnibfc/160-homepage-songs-for-every-occasion-section-sub- …
=> FIXED HOMEPAGE

src/components/Home/FAQ.vue
https://trello.com/c/UILRyMnT/172-faq-section-changes-in-content
=> Updated FAQ section | Changes in content

src/views/Homepage/Artist.vue
=> Artist Page failed to load artist list

src/components/Events/Card.vue, src/style.css, src/views/Homepage/Event.vue
- https://trello.com/c/Sz614dS4/161-events-make-events-card-uniform-in-size
- https://trello.com/c/3KUr0aIf/119-events-page-events-card-resize-the-text-font-on-seeking-for-and-performer
=> fix  ( ….) is still placed on the next line of the Card and make card uniform in size

src/style.css
- decrease padding on laptop sizes
=> decrease padding on laptop sizes

src/assets/css/artist-ui.css
- fix overlapping button add member
=> fix overlapping button
